name: sip_cli
version: 0.4.6
description: Manage mono-repos with `sip`, run scripts and get dependencies concurrently.
homepage: https://github.com/mrgnhnt96/sip
repository: https://github.com/mrgnhnt96/sip/tree/main/packages/sip
issue_tracker: https://github.com/mrgnhnt96/sip/issues
documentation: https://github.com/mrgnhnt96/sip/tree/master/packages/sip#readme
topics: [cli, executable, dependencies, mono-repo]
platforms:
  linux:
  macos:
  windows:

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: ">=2.0.0 <2.5.0"
  file: ">=6.0.0 <8.0.0"
  glob: ">=2.0.0 <3.0.0"
  mason_logger: ">=0.0.1 <1.0.0"
  path: ">=1.8.0 <2.0.0"
  pub_updater: ^0.4.0
  sip_script_runner: ">=0.0.1 <1.0.0"
  yaml: ">=3.0.0 <4.0.0"

dev_dependencies:
  barreler: ^1.0.1
  build_runner: ^2.4.8
  build_version: ^2.1.1
  mocktail: ^1.0.3
  pana: ^0.22.2
  test: ^1.25.1
  very_good_analysis: ^5.1.0

executables:
  sip:
