name: sip_cli
version: 0.18.0-pre
description: Manage mono-repos with `sip`, run scripts and get dependencies concurrently.
homepage: https://github.com/mrgnhnt96/sip
repository: https://github.com/mrgnhnt96/sip/tree/main/packages/sip
issue_tracker: https://github.com/mrgnhnt96/sip/issues
documentation: https://github.com/mrgnhnt96/sip/tree/master/packages/sip#readme
topics: [cli, executable, dependencies, mono-repo]
funding:
  - https://github.com/sponsors/mrgnhnt96
platforms:
  linux:
  macos:
  windows:

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  file: ">=6.0.0 <8.0.0"
  glob: ">=2.0.0 <3.0.0"
  lukehog_client: ^0.4.6
  mason_logger: ">=0.0.1 <1.0.0"
  meta: ^1.17.0
  path: ">=1.8.0 <2.0.0"
  platform: ^3.1.6
  pub_semver: ^2.1.4
  pub_updater: ^0.5.0
  scoped_deps: ^0.1.0+2
  yaml: ">=3.0.0 <4.0.0"
  yaml_edit: ^2.2.1

dev_dependencies:
  hooksman: ^3.0.0
  mocktail: ^1.0.3
  pana: ^0.22.2
  test: ^1.25.1
  very_good_analysis: ^6.0.0

executables:
  sip:
