name: sip_script_runner
version: 0.0.17
description: The core package for sip, used to parse and run project commands/scripts
homepage: https://github.com/mrgnhnt96/sip
repository: https://github.com/mrgnhnt96/sip/tree/main/packages/script_runner
issue_tracker: https://github.com/mrgnhnt96/sip/issues
documentation: https://github.com/mrgnhnt96/sip/tree/master/packages/sip#readme
topics: [cli, executable, sip]
platforms:
  linux:
  macos:
  windows:

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  autoequal: ">=0.9.0 <1.0.0"
  equatable: ">=2.0.0 <3.0.0"
  ffi: ">=2.0.0 <3.0.0"
  get_it: ">=7.0.0 <8.0.0"
  json_annotation: ">=4.0.0 <5.0.0"
  path: ">=1.8.0 <2.0.0"
  sip_console: ">=0.0.1 <0.1.0"
  yaml: ">=3.0.0 <4.0.0"

dev_dependencies:
  autoequal_gen: ^0.9.0
  build_runner: ^2.4.8
  build_version: ^2.1.1
  json_serializable: ^6.7.1
  mocktail: ^1.0.3
  test: ^1.25.1
